# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/benjamin/Documents/git/AdRecognition

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/benjamin/Documents/git/AdRecognition

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benjamin/Documents/git/AdRecognition/CMakeFiles /home/benjamin/Documents/git/AdRecognition/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/benjamin/Documents/git/AdRecognition/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ./bin/selectlines

# Build rule for target.
./bin/selectlines: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/selectlines
.PHONY : ./bin/selectlines

# fast build rule for target.
./bin/selectlines/fast:
	$(MAKE) -f CMakeFiles/./bin/selectlines.dir/build.make CMakeFiles/./bin/selectlines.dir/build
.PHONY : ./bin/selectlines/fast

#=============================================================================
# Target rules for targets named ./bin/selectRatio

# Build rule for target.
./bin/selectRatio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/selectRatio
.PHONY : ./bin/selectRatio

# fast build rule for target.
./bin/selectRatio/fast:
	$(MAKE) -f CMakeFiles/./bin/selectRatio.dir/build.make CMakeFiles/./bin/selectRatio.dir/build
.PHONY : ./bin/selectRatio/fast

#=============================================================================
# Target rules for targets named ./bin/modelTester

# Build rule for target.
./bin/modelTester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/modelTester
.PHONY : ./bin/modelTester

# fast build rule for target.
./bin/modelTester/fast:
	$(MAKE) -f CMakeFiles/./bin/modelTester.dir/build.make CMakeFiles/./bin/modelTester.dir/build
.PHONY : ./bin/modelTester/fast

#=============================================================================
# Target rules for targets named ./bin/svm_test

# Build rule for target.
./bin/svm_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/svm_test
.PHONY : ./bin/svm_test

# fast build rule for target.
./bin/svm_test/fast:
	$(MAKE) -f CMakeFiles/./bin/svm_test.dir/build.make CMakeFiles/./bin/svm_test.dir/build
.PHONY : ./bin/svm_test/fast

#=============================================================================
# Target rules for targets named ./bin/randomForest_test

# Build rule for target.
./bin/randomForest_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/randomForest_test
.PHONY : ./bin/randomForest_test

# fast build rule for target.
./bin/randomForest_test/fast:
	$(MAKE) -f CMakeFiles/./bin/randomForest_test.dir/build.make CMakeFiles/./bin/randomForest_test.dir/build
.PHONY : ./bin/randomForest_test/fast

#=============================================================================
# Target rules for targets named ./bin/randomize

# Build rule for target.
./bin/randomize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/randomize
.PHONY : ./bin/randomize

# fast build rule for target.
./bin/randomize/fast:
	$(MAKE) -f CMakeFiles/./bin/randomize.dir/build.make CMakeFiles/./bin/randomize.dir/build
.PHONY : ./bin/randomize/fast

#=============================================================================
# Target rules for targets named ./bin/neuralNetwork_test

# Build rule for target.
./bin/neuralNetwork_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./bin/neuralNetwork_test
.PHONY : ./bin/neuralNetwork_test

# fast build rule for target.
./bin/neuralNetwork_test/fast:
	$(MAKE) -f CMakeFiles/./bin/neuralNetwork_test.dir/build.make CMakeFiles/./bin/neuralNetwork_test.dir/build
.PHONY : ./bin/neuralNetwork_test/fast

src/modelTester.o: src/modelTester.cpp.o

.PHONY : src/modelTester.o

# target to build an object file
src/modelTester.cpp.o:
	$(MAKE) -f CMakeFiles/./bin/modelTester.dir/build.make CMakeFiles/./bin/modelTester.dir/src/modelTester.cpp.o
.PHONY : src/modelTester.cpp.o

src/modelTester.i: src/modelTester.cpp.i

.PHONY : src/modelTester.i

# target to preprocess a source file
src/modelTester.cpp.i:
	$(MAKE) -f CMakeFiles/./bin/modelTester.dir/build.make CMakeFiles/./bin/modelTester.dir/src/modelTester.cpp.i
.PHONY : src/modelTester.cpp.i

src/modelTester.s: src/modelTester.cpp.s

.PHONY : src/modelTester.s

# target to generate assembly for a file
src/modelTester.cpp.s:
	$(MAKE) -f CMakeFiles/./bin/modelTester.dir/build.make CMakeFiles/./bin/modelTester.dir/src/modelTester.cpp.s
.PHONY : src/modelTester.cpp.s

src/neuralNetwork.o: src/neuralNetwork.cpp.o

.PHONY : src/neuralNetwork.o

# target to build an object file
src/neuralNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/./bin/neuralNetwork_test.dir/build.make CMakeFiles/./bin/neuralNetwork_test.dir/src/neuralNetwork.cpp.o
.PHONY : src/neuralNetwork.cpp.o

src/neuralNetwork.i: src/neuralNetwork.cpp.i

.PHONY : src/neuralNetwork.i

# target to preprocess a source file
src/neuralNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/./bin/neuralNetwork_test.dir/build.make CMakeFiles/./bin/neuralNetwork_test.dir/src/neuralNetwork.cpp.i
.PHONY : src/neuralNetwork.cpp.i

src/neuralNetwork.s: src/neuralNetwork.cpp.s

.PHONY : src/neuralNetwork.s

# target to generate assembly for a file
src/neuralNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/./bin/neuralNetwork_test.dir/build.make CMakeFiles/./bin/neuralNetwork_test.dir/src/neuralNetwork.cpp.s
.PHONY : src/neuralNetwork.cpp.s

src/randomForest.o: src/randomForest.cpp.o

.PHONY : src/randomForest.o

# target to build an object file
src/randomForest.cpp.o:
	$(MAKE) -f CMakeFiles/./bin/randomForest_test.dir/build.make CMakeFiles/./bin/randomForest_test.dir/src/randomForest.cpp.o
.PHONY : src/randomForest.cpp.o

src/randomForest.i: src/randomForest.cpp.i

.PHONY : src/randomForest.i

# target to preprocess a source file
src/randomForest.cpp.i:
	$(MAKE) -f CMakeFiles/./bin/randomForest_test.dir/build.make CMakeFiles/./bin/randomForest_test.dir/src/randomForest.cpp.i
.PHONY : src/randomForest.cpp.i

src/randomForest.s: src/randomForest.cpp.s

.PHONY : src/randomForest.s

# target to generate assembly for a file
src/randomForest.cpp.s:
	$(MAKE) -f CMakeFiles/./bin/randomForest_test.dir/build.make CMakeFiles/./bin/randomForest_test.dir/src/randomForest.cpp.s
.PHONY : src/randomForest.cpp.s

src/randomize.o: src/randomize.cpp.o

.PHONY : src/randomize.o

# target to build an object file
src/randomize.cpp.o:
	$(MAKE) -f CMakeFiles/./bin/randomize.dir/build.make CMakeFiles/./bin/randomize.dir/src/randomize.cpp.o
.PHONY : src/randomize.cpp.o

src/randomize.i: src/randomize.cpp.i

.PHONY : src/randomize.i

# target to preprocess a source file
src/randomize.cpp.i:
	$(MAKE) -f CMakeFiles/./bin/randomize.dir/build.make CMakeFiles/./bin/randomize.dir/src/randomize.cpp.i
.PHONY : src/randomize.cpp.i

src/randomize.s: src/randomize.cpp.s

.PHONY : src/randomize.s

# target to generate assembly for a file
src/randomize.cpp.s:
	$(MAKE) -f CMakeFiles/./bin/randomize.dir/build.make CMakeFiles/./bin/randomize.dir/src/randomize.cpp.s
.PHONY : src/randomize.cpp.s

src/selectRatio.o: src/selectRatio.cpp.o

.PHONY : src/selectRatio.o

# target to build an object file
src/selectRatio.cpp.o:
	$(MAKE) -f CMakeFiles/./bin/selectRatio.dir/build.make CMakeFiles/./bin/selectRatio.dir/src/selectRatio.cpp.o
.PHONY : src/selectRatio.cpp.o

src/selectRatio.i: src/selectRatio.cpp.i

.PHONY : src/selectRatio.i

# target to preprocess a source file
src/selectRatio.cpp.i:
	$(MAKE) -f CMakeFiles/./bin/selectRatio.dir/build.make CMakeFiles/./bin/selectRatio.dir/src/selectRatio.cpp.i
.PHONY : src/selectRatio.cpp.i

src/selectRatio.s: src/selectRatio.cpp.s

.PHONY : src/selectRatio.s

# target to generate assembly for a file
src/selectRatio.cpp.s:
	$(MAKE) -f CMakeFiles/./bin/selectRatio.dir/build.make CMakeFiles/./bin/selectRatio.dir/src/selectRatio.cpp.s
.PHONY : src/selectRatio.cpp.s

src/selectlines.o: src/selectlines.cpp.o

.PHONY : src/selectlines.o

# target to build an object file
src/selectlines.cpp.o:
	$(MAKE) -f CMakeFiles/./bin/selectlines.dir/build.make CMakeFiles/./bin/selectlines.dir/src/selectlines.cpp.o
.PHONY : src/selectlines.cpp.o

src/selectlines.i: src/selectlines.cpp.i

.PHONY : src/selectlines.i

# target to preprocess a source file
src/selectlines.cpp.i:
	$(MAKE) -f CMakeFiles/./bin/selectlines.dir/build.make CMakeFiles/./bin/selectlines.dir/src/selectlines.cpp.i
.PHONY : src/selectlines.cpp.i

src/selectlines.s: src/selectlines.cpp.s

.PHONY : src/selectlines.s

# target to generate assembly for a file
src/selectlines.cpp.s:
	$(MAKE) -f CMakeFiles/./bin/selectlines.dir/build.make CMakeFiles/./bin/selectlines.dir/src/selectlines.cpp.s
.PHONY : src/selectlines.cpp.s

src/svm.o: src/svm.cpp.o

.PHONY : src/svm.o

# target to build an object file
src/svm.cpp.o:
	$(MAKE) -f CMakeFiles/./bin/svm_test.dir/build.make CMakeFiles/./bin/svm_test.dir/src/svm.cpp.o
.PHONY : src/svm.cpp.o

src/svm.i: src/svm.cpp.i

.PHONY : src/svm.i

# target to preprocess a source file
src/svm.cpp.i:
	$(MAKE) -f CMakeFiles/./bin/svm_test.dir/build.make CMakeFiles/./bin/svm_test.dir/src/svm.cpp.i
.PHONY : src/svm.cpp.i

src/svm.s: src/svm.cpp.s

.PHONY : src/svm.s

# target to generate assembly for a file
src/svm.cpp.s:
	$(MAKE) -f CMakeFiles/./bin/svm_test.dir/build.make CMakeFiles/./bin/svm_test.dir/src/svm.cpp.s
.PHONY : src/svm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ./bin/selectlines"
	@echo "... ./bin/selectRatio"
	@echo "... ./bin/modelTester"
	@echo "... ./bin/svm_test"
	@echo "... ./bin/randomForest_test"
	@echo "... ./bin/randomize"
	@echo "... edit_cache"
	@echo "... ./bin/neuralNetwork_test"
	@echo "... src/modelTester.o"
	@echo "... src/modelTester.i"
	@echo "... src/modelTester.s"
	@echo "... src/neuralNetwork.o"
	@echo "... src/neuralNetwork.i"
	@echo "... src/neuralNetwork.s"
	@echo "... src/randomForest.o"
	@echo "... src/randomForest.i"
	@echo "... src/randomForest.s"
	@echo "... src/randomize.o"
	@echo "... src/randomize.i"
	@echo "... src/randomize.s"
	@echo "... src/selectRatio.o"
	@echo "... src/selectRatio.i"
	@echo "... src/selectRatio.s"
	@echo "... src/selectlines.o"
	@echo "... src/selectlines.i"
	@echo "... src/selectlines.s"
	@echo "... src/svm.o"
	@echo "... src/svm.i"
	@echo "... src/svm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

